plugins:
    - prettier
env:
    browser: true
    es2021: true
extends:
    - eslint:recommended
parserOptions:
    ecmaVersion: 12
    sourceType: module
rules:
    curly: error
    no-var: error
    prettier/prettier: error
overrides:
    - files:
          - pug.config.js
      env:
          node: true
